sudo: false

language: python

cache: 
    directories:
        - $HOME/.cache/pip

python:
- '2.7'
- '3.4'

addons:
  apt:
    packages:
    - libatlas-base-dev
    - gfortran


before_install:
    - mkdir -p $HOME/.cache/pip/wheels
    - travis_wait pip wheel --find-links=$HOME/.cache/pip/wheels --use-wheel --wheel-dir=$HOME/.cache/pip/wheels scipy
    - pip install --no-index --find-links=$HOME/.cache/pip/wheels scipy

script:
- nosetests -vv --with-coverage --cover-package=flownetpy

after_success:
- if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then coveralls; fi

deploy:
  provider: pypi
  user: dmanik
  password:
    secure: otODHgQzggAUDamHsRB29OwKObY96Be7z9TPwx3lDadyvuBYfTi2v3uRi9CYMUkWqahn1CpLii0Y1ob5MCEi1lWTPHgjj1VN+xizt/DusiLYsV5ShiLwG1eaHbir0gumugW71vy4HJBipBG5fErleJQQcPO39Sb79FsiYSSPVhQBc42q6Mpisl2fZK84Kg1dV9ADoFxmcZwSjwjZvB8dZt2rnxLGgb9MOnawRXUpWju7PlsuVx4vQ591TAtZIvkuNPjg7CfCaK6IfiDHn0M/76PtcZllJOo6VkfSEZhWAQBZDFD5WnUdCG4Qc2z2Xh4W/jSsvgpPCaGFNz1rglZdMzmCZKSewBil1GKc6gnIBs4AsjaZpXuOZbat+CvgyuAlLgepJPFsykRBa526G2vQ0yENggwfji6lgmJIqzehNkm2NHuadBdCrTaN7jHjJERbb6gn3DNU+mT1PibIJUoFz7dLI+xiwiXIve9fIofv3Da5NuTo45s4fVqX2Xd6m2oyd7HJOKaCn/YrIXjTu/TPQ8oRK5M05R3oGV4ZrFVTFRX3+tGdxb/NlVoDEOPZ/g8AQ7FkgBWfPbEcPxw+RRlybjzZOoxt7zRqwJGvy+ZSUcA6hTtlJcWkIwuV32ghztSC7fVKMMQPwaIZgyq9eMB4hMCSsm/5ZF48P9udr/WlqnY=
  on:
    tags: true
    repo: debsankha/flownetpy
