language: python

python:
          - "2.7"
          - "2.7"
          - "3.2"
          - "3.3"
          - "3.4"

before_install:
          - sudo apt-get update -qq
          - sudo apt-get install -y libatlas-base-dev gfortran python-numpy python-scipy python3-numpy python3-scipy


install: "pip install hypothesis networkx" 

script:
          - nosetests

