language:
    python

python:
    - "2.7"
    - "3.4"

addons:
    apt:
        packages:
            - python-scipy
            - python3-scipy

install:
    - pip install hypothesis networkx

script:
    - nosetests -vv flownetpy/tests/flowmodels/

