language:
    python

python:
    - "2.7"
    - "3.4"
addons:
    apt:
        packages: 
          - libatlas-base-dev
          - gfortran

install:
    - pip install hypothesis networkx scipy numpy

script:
    - nosetests -vv 

