language:
    python

python:
    - "2.7"
    - "3.4"

addons:
    apt:
        packages:
            - python-scipy
            - python3-scipy

before_install:
    - pip install hypothesis networkx

install:
    - python setup.py install   

script:
        - nosetests -v

