
sudo: false

language: python

python:
- '2.7'
- '3.4'

addons:
  apt:
    packages:
    - libatlas-base-dev
    - gfortran


before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION scipy
  # Coverage packages are on my binstar channel
  - pip install numpy networkx hypothesis

script:
- nosetests -vv

deploy:
  provider: pypi
  user: dmanik
  password:
    secure: otODHgQzggAUDamHsRB29OwKObY96Be7z9TPwx3lDadyvuBYfTi2v3uRi9CYMUkWqahn1CpLii0Y1ob5MCEi1lWTPHgjj1VN+xizt/DusiLYsV5ShiLwG1eaHbir0gumugW71vy4HJBipBG5fErleJQQcPO39Sb79FsiYSSPVhQBc42q6Mpisl2fZK84Kg1dV9ADoFxmcZwSjwjZvB8dZt2rnxLGgb9MOnawRXUpWju7PlsuVx4vQ591TAtZIvkuNPjg7CfCaK6IfiDHn0M/76PtcZllJOo6VkfSEZhWAQBZDFD5WnUdCG4Qc2z2Xh4W/jSsvgpPCaGFNz1rglZdMzmCZKSewBil1GKc6gnIBs4AsjaZpXuOZbat+CvgyuAlLgepJPFsykRBa526G2vQ0yENggwfji6lgmJIqzehNkm2NHuadBdCrTaN7jHjJERbb6gn3DNU+mT1PibIJUoFz7dLI+xiwiXIve9fIofv3Da5NuTo45s4fVqX2Xd6m2oyd7HJOKaCn/YrIXjTu/TPQ8oRK5M05R3oGV4ZrFVTFRX3+tGdxb/NlVoDEOPZ/g8AQ7FkgBWfPbEcPxw+RRlybjzZOoxt7zRqwJGvy+ZSUcA6hTtlJcWkIwuV32ghztSC7fVKMMQPwaIZgyq9eMB4hMCSsm/5ZF48P9udr/WlqnY=
  on:
    tags: true
    repo: debsankha/flownetpy
