language: python

python:
          - "2.7"
          - "2.7"
          - "3.2"
          - "3.3"
          - "3.4"

install: "pip install numpy scipy hypothesis networkx" 

script:
          - nosetests

